version: "3"

services:
  db:
    image: postgres:16
    container_name: myapp-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
